[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-request-camera-permission",
  "allow-get-available-cameras",
  "allow-start-streaming",
  "allow-stop-streaming",
  "allow-initialize",
  "allow-start-camera-webrtc-session",
  "allow-set-remote-description",
  "allow-add-ice-candidate",
  "allow-close-connection"
]
