[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-ping",
  "allow-request-camera-permission",
  "allow-get-available-cameras",
  "allow-start-streaming",
  "allow-stop-streaming",
  "allow-capture-frame",
  "allow-get-stream-format"
]
