[default]
description = "Default permissions for the plugin"
permissions = [
  "allow_request_camera_permission",
  "allow_get_available_cameras",
  "allow_start_streaming",
  "allow_stop_streaming",
  "allow_initialize"
]
