[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-request-camera-permission",
  "allow-get-available-cameras",
  "allow-start-streaming",
  "allow-stop-streaming",
  "allow-initialize",
  "allow-start_camera_webrtc_session",
  "allow-set_remote_description",
  "allow-add_ice_candidate",
  "allow-close_connection"
]
