[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-request_camera_permission",
  "allow-get_available_cameras",
  "allow-start_streaming",
  "allow-stop_streaming",
  "allow-initialize",
  "allow-start_camera_webrtc_session",
  "allow-set_remote_description",
  "allow-add_ice_candidate",
  "allow-close_connection"
]
